version: '3'

services:
  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db

  item-app:
    image: rosyid/item-app:v1
    ports:
      - 80:8080
    restart: always

volumes:
  app-db:
